mode_1:
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 1
    out_channels: 1

  train:
    data:
      datapath: '/project/MLFluids/NS_fft_Re500_T4000.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 1
      offset: 0
      n_sample: 400
      time_interval: 0.5
      nx: 64
      nt: 64
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 1
    epochs: 40000
    milestones: [10000, 20000, 30000]
    base_lr: 0.001
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: '4C0_v1'
    data_iter: 4

  eval:
    data:
      datapath: '/project/MLFluids/NS_fine_Re500_T128_part2.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 300
      time_interval: 0.5
      nx: 128
      nt: 128
      sub: 1
      sub_t: 1
      shuffle: False
    batchsize: 1
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: 'val_T64_R256_sub1'

  fine:
    data:
      datapath: '/project/MLFluids//NS_Re500_s256_T100_test.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 1
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: True
    batchsize: 1
    epochs: 2500
    milestones: [1000, 1500, 2000]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: 'fine_T100_R256'
    data_iter: 4