debug:
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 1
    out_channels: 1

  train:
    data:
      datapath: '/project/MLFluids/NS_fft_Re500_T4000.npy' #'/project/MLFluids/NS_fft_Re500_T4000_cartesian.npy'
      problem_type: 'vorticity_periodic'
      Re: 500
      total_num: 4000
      offset: 0
      n_sample: 400
      time_interval: 0.5
      nx: 64
      nt: 64
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 2
    epochs: 40000
    milestones: [10000, 20000, 30000]
    base_lr: 0.001
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'rearchitecture_debug'
    save_name: 'train'
    data_iter: 4
    loss_type: 'LPLoss'
    pino_scheme: '4th Order Periodic' # select from ('2nd Order Periodic', '4th Order Periodic', 'Torch.Gradient', 'Spectral')

  eval:
    data:
      datapath: '/project/MLFluids/NS_fine_Re500_T128_part2.npy'
      problem_type: 'vorticity_periodic'
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 300
      time_interval: 0.5
      nx: 128
      nt: 128
      sub: 1
      sub_t: 1
      shuffle: False
    batchsize: 2
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'rearchitecture_debug'
    save_name: 'train'
    data_iter: 1
    loss_type: 'LPLoss'
    pino_scheme: '4th Order Periodic' # select from ('2nd Order Periodic', '4th Order Periodic', 'Torch.Gradient', 'Spectral')

  fine:
    data:
      datapath: '/project/MLFluids/NS_fine_Re500_T128_part2.npy' #'/project/MLFluids//NS_Re500_s256_T100_test.npy'
      problem_type: 'vorticity_periodic' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 1
      time_interval: 0.5
      nx: 128
      nt: 128
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 1
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    epochs: 2500
    milestones: [1000, 1500, 2000]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 5.0
    f_loss: 1.0
    xy_loss: 0
    save_dir: 'rearchitecture_debug'
    save_name: 'fine'
    data_iter: 4
    loss_type: 'LPLoss'
    pino_scheme: '4th Order Periodic' # select from ('2nd Order Periodic', '4th Order Periodic', 'Torch.Gradient', 'Spectral')


mode_1: # Vorticity Flow
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 1
    out_channels: 1

  train:
    data:
      datapath: '/project/MLFluids/NS_fft_Re500_T4000.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 1
      offset: 0
      n_sample: 400
      time_interval: 0.5
      nx: 64
      nt: 64
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 1
    epochs: 40000
    milestones: [10000, 20000, 30000]
    base_lr: 0.001
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: '4C0_v1'
    data_iter: 4

  eval:
    data:
      datapath: '/project/MLFluids/NS_fine_Re500_T128_part2.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 300
      time_interval: 0.5
      nx: 128
      nt: 128
      sub: 1
      sub_t: 1
      shuffle: False
    batchsize: 1
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: 'val_T64_R256_sub1'

  fine:
    data:
      datapath: '/project/MLFluids//NS_Re500_s256_T100_test.npy'
      problem_type: 'vorticity_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 1
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: True
    batchsize: 1
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    epochs: 2500
    milestones: [1000, 1500, 2000]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 5.0
    f_loss: 1.0
    xy_loss: 0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: 'fine_T100_R256'
    data_iter: 4

mode_2: # Cavity Flow
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 2
    out_channels: 2

  train:
    data:
      datapath: '/project/MLFluids/cavity.npy'
      problem_type: 'cavity' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 1
      offset: 0
      n_sample: 1
      time_interval: 1
      nx: 256
      nt: 1000 #1000
      sub: 4
      sub_t: 20
      shuffle: True
    batchsize: 1
    epochs: 5000
    milestones: [500, 1000, 1500, 2000, 2500, 3000, 3500, 4000, 4500]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 0.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: '4C0_v1'
    data_iter: 1

  void_eval:
    data:
      datapath: '/project/MLFluids/NS_fine_Re500_T128_part2.npy'
      problem_type: 'cavity' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 300
      time_interval: 0.5
      nx: 128
      nt: 128
      sub: 1
      sub_t: 1
      shuffle: False
    batchsize: 1
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM'
    save_name: 'val_T64_R256_sub1'

mode_3: # Cartesian Flow
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 2
    out_channels: 2

  train:
    data:
      datapath: '/project/MLFluids/NS_fft_Re500_T4000_cartesian.npy'
      problem_type: 'cartesian_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 4000
      offset: 0
      n_sample: 400
      time_interval: 0.5
      nx: 64
      nt: 64
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 2
    epochs: 40000
    milestones: [10000, 20000, 30000]
    base_lr: 0.001
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v5'
    save_name: '4C0_v1-cartesian'
    data_iter: 4

  eval:
    data:
      datapath: '/project/MLFluids/NS_Re500_s256_T100_test_cartesian.npy'
      problem_type: 'cartesian_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 20
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: False
    batchsize: 2
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v5'
    save_name: 'val_s256_T100-cartesian'

  fine: #RuntimeError: CUDA out of memory. Tried to allocate 4.50 GiB (GPU 0; 15.78 GiB total capacity; 7.82 GiB alr$
    data:
      datapath: '/project/MLFluids/NS_Re500_s256_T100_test_cartesian.npy'
      problem_type: 'cartesian_periodic_short' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 2
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: True
    batchsize: 2
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    epochs: 2500
    milestones: [1000, 1500, 2000]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 5.0
    f_loss: 1.0
    xy_loss: 0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v5'
    save_name: 'fine_s256_T100-cartesian'
    data_iter: 4


mode_4: # Cartesian Flow
  model:
    layers: [64, 64, 64, 64, 64]
    modes1: [8, 8, 8, 8]
    modes2: [8, 8, 8, 8]
    modes3: [8, 8, 8, 8]
    fc_dim: 128
    in_channels: 2
    out_channels: 2

  train:
    data:
      datapath: '/project/MLFluids/NS_fft_Re500_T4000_cartesian.npy'
      problem_type: 'cartesian_to_vorticity_trial' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 4000
      offset: 0
      n_sample: 400
      time_interval: 0.5
      nx: 64
      nt: 64
      sub: 1
      sub_t: 1
      shuffle: True
    batchsize: 2
    epochs: 40000
    milestones: [10000, 20000, 30000]
    base_lr: 0.001
    scheduler_gamma: 0.5
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v7'
    save_name: '4C0_v1-cartesian'
    data_iter: 4

  eval:
    data:
      datapath: '/project/MLFluids/NS_Re500_s256_T100_test_cartesian.npy'
      problem_type: 'cartesian_to_vorticity_trial' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 20
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: False
    batchsize: 2
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    ic_loss: 1.0
    f_loss: 1.0
    xy_loss: 5.0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v7'
    save_name: 'val_s256_T100-cartesian'

  fine: #RuntimeError: CUDA out of memory. Tried to allocate 4.50 GiB (GPU 0; 15.78 GiB total capacity; 7.82 GiB alr$
    data:
      datapath: '/project/MLFluids/NS_Re500_s256_T100_test_cartesian.npy'
      problem_type: 'cartesian_to_vorticity_trial' # select from (vorticity_periodic_short, cartesian_periodic_short, cavity)
      Re: 500
      total_num: 100
      offset: 0
      n_sample: 2
      time_interval: 0.5
      nx: 256
      nt: 128
      sub: 2
      sub_t: 1
      shuffle: True
    batchsize: 2
    #ckpt: '/home/cfos3120/checkpoints/Re500-FDM/4C0_v1.pt'
    epochs: 2500
    milestones: [1000, 1500, 2000]
    base_lr: 0.0025
    scheduler_gamma: 0.5
    ic_loss: 5.0
    f_loss: 1.0
    xy_loss: 0
    save_dir: 'Lasso_1_Re500-FDM-cartesian_v7'
    save_name: 'fine_s256_T100-cartesian'
    data_iter: 4